function myFunction(numberOfChildren, partnerName, location, job){
    console.log("You will be a " + job + " in " + location + " ,and married to " + partnerName + " with " + numberOfChildren + " kids")

}
function calculate(currentYear, birthYear){
    console.log("They are " + (birthYear-currentYear) +  " years old")


}

function circle(radius){
    console.log("The circumference is " + (3.14*2*radius))
    console.log("The Area is " + (3.14*radius*radius))

}